from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from speace_core.cellular_brain.memory.episodic_memory import Episode


class EpisodeSummarizer:
    """T47 — Summarize and classify episodes."""

    def __init__(self, report_dir: str = "reports/episodic_memory"):
        self.report_dir = Path(report_dir)
        self.report_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ #
    # Classification
    # ------------------------------------------------------------------ #

    @staticmethod
    def classify(episode: Episode) -> str:
        event_types = {ev.event_type for ev in episode.events}

        if "self_improvement" in episode.trigger or any(
            "self_improvement" in et for et in event_types
        ):
            return "SELF_IMPROVEMENT_EPISODE"

        if any(
            et in event_types
            for et in (
                "assembly_association_created",
                "cell_assembly_created",
                "cell_assembly_reinforced",
                "semantic_recall_succeeded",
            )
        ):
            return "SEMANTIC_LEARNING_EPISODE"

        if any(
            et in event_types
            for et in (
                "brainstem_stability_override",
                "region_stability_checked",
                "cellular_repair_succeeded",
                "cellular_defense_applied",
            )
        ):
            return "STABILITY_EPISODE"

        if episode.cognitive_delta < -0.03 or episode.phi_delta < -0.03:
            return "REGRESSION_EPISODE"

        if episode.cognitive_delta > 0 or episode.phi_delta > 0.02:
            return "RECOVERY_EPISODE"

        return "NEUTRAL_EPISODE"

    # ------------------------------------------------------------------ #
    # Markdown report
    # ------------------------------------------------------------------ #

    def generate_markdown_report(self, episode: Episode) -> str:
        classification = self.classify(episode)
        lines = [
            f"# Episode Report: {episode.episode_id}",
            "",
            f"**Classification:** {classification}",
            f"**Trigger:** {episode.trigger}",
            f"**Outcome:** {episode.outcome}",
            f"**Start:** {episode.start_time}",
            f"**End:** {episode.end_time or 'open'}",
            f"**Event Count:** {len(episode.events)}",
            "",
            "## Metric Deltas",
            f"- Cognitive Δ: {episode.cognitive_delta:+.4f}",
            f"- Φ Δ: {episode.phi_delta:+.4f}",
            f"- Energy Δ: {episode.energy_delta:+.4f}",
            "",
            "## Events",
        ]
        for ev in episode.events:
            lines.append(
                f"- [{ev.timestamp}] {ev.event_type} ({ev.source_module})"
            )

        if episode.linked_assemblies:
            lines.extend(["", "## Linked Assemblies", ", ".join(episode.linked_assemblies)])
        if episode.linked_proposals:
            lines.extend(["", "## Linked Proposals", ", ".join(episode.linked_proposals)])
        if episode.semantic_tags:
            lines.extend(["", "## Semantic Tags", ", ".join(episode.semantic_tags)])

        lines.extend(["", "---", "*Generated by T47 EpisodeSummarizer*"])
        return "\n".join(lines)

    def generate_batch_markdown_report(self, episodes: List[Episode]) -> str:
        lines = ["# T47 — Episodic Memory Batch Report", ""]
        counts: Dict[str, int] = {}
        for ep in episodes:
            cls = self.classify(ep)
            counts[cls] = counts.get(cls, 0) + 1

        lines.append("## Classification Counts")
        for cls, count in sorted(counts.items()):
            lines.append(f"- {cls}: {count}")

        lines.extend(["", "## Episodes"])
        for ep in episodes:
            lines.append(f"\n### {ep.episode_id} ({self.classify(ep)})")
            lines.append(f"- Trigger: {ep.trigger}")
            lines.append(f"- Outcome: {ep.outcome}")
            lines.append(f"- Events: {len(ep.events)}")
            lines.append(f"- Cognitive Δ: {ep.cognitive_delta:+.4f}")

        lines.extend(["", "---", "*Generated by T47 EpisodeSummarizer*"])
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # File output
    # ------------------------------------------------------------------ #

    def save_report(self, episode: Episode) -> Path:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        path = self.report_dir / f"episode_{episode.episode_id}_{timestamp}.md"
        path.write_text(self.generate_markdown_report(episode), encoding="utf-8")
        return path
