"""Q-SPEACE — Quantum Super Planetary Entità Autonoma Cibernetica.

Quantum layer for the SPEACE organism: numpy quantum kernel, EDD-CVT
(ILF + Cosmic Viruses), fractal QCA, earth-signal feed, energy cost model
and a quantum orchestrator. See progetto_q_speace_linee_guida.md.
"""
from __future__ import annotations

from .bcel import BCELCatalog
from .earth_feed import EarthFeed, EarthSignals
from .edd_cvt import CosmicVirusOptimizer, CVConfig, InformationalLogicalField
from .fractal_qca import FractalQCA
from .fractal_qca_cascade import (
    FractalQCACascade,
    LevelSignature,
    MacroLevel,
    experiment_cross_scale,
    qi_bridge_cqasm,
)
from .genome import QuantumGeneSet
from .metabolism import QuantumCostModel, QuantumOperation
from .orchestrator import QuantumOrchestrator, TickReport
from .quantum import (
    BrainQuantumCircuit,
    EntangledPair,
    EntanglementRegistry,
    GateType,
    MeasurementResult,
    QuantumBrainSimulator,
    QuantumGates,
    QuantumNeuralBridge,
    QuantumState,
)
from .schumann import run_schumann, schumann_circuit
from .self_improvement_cortex import (
    AdaptiveLevel,
    AdaptiveLevelRegistry,
    AgentProposal,
    DigitalDNAAgent,
    DNAMutationRecord,
    EpigeneticEngine,
    EpigeneticMarker,
    EpigeneticState,
    EpigeneticTag,
    EvolutionaryMemory,
    EvolutionCouncil,
    EvolutionOrchestrator,
    HarnessUpdate,
    ILFAgent,
    ILFRegulator,
    MemoryAgent,
    MemoryEntry,
    MutationAgent,
    MutationRegistry,
    MutationVerdict,
    NeurogenesisPipeline,
    NeuroscienceAgent,
    NewModuleSpec,
    OrganismObserver,
    PhysiologicalProfile,
    QAOASelector,
    QuantumEvolutionEngine,
    QuantumKernelClassifier,
    QuantumOracle,
    RLAgent,
    RollbackManager,
    RollbackPlan,
    SafetyAgent,
    SelfImprovementCortex,
    SoftwareArchitect,
    WeightUpdate,
)

__all__ = [
    "QuantumState",
    "QuantumGates",
    "GateType",
    "EntanglementRegistry",
    "EntangledPair",
    "BrainQuantumCircuit",
    "QuantumBrainSimulator",
    "QuantumNeuralBridge",
    "MeasurementResult",
    "QuantumGeneSet",
    "QuantumCostModel",
    "QuantumOperation",
    "InformationalLogicalField",
    "CosmicVirusOptimizer",
    "CVConfig",
    "FractalQCA",
    "FractalQCACascade",
    "LevelSignature",
    "MacroLevel",
    "experiment_cross_scale",
    "qi_bridge_cqasm",
    "EarthFeed",
    "EarthSignals",
    "QuantumOrchestrator",
    "TickReport",
    "BCELCatalog",
    "run_schumann",
    "schumann_circuit",
    "SelfImprovementCortex",
    "EvolutionCouncil",
    "EvolutionOrchestrator",
    "NeuroscienceAgent",
    "SoftwareArchitect",
    "RLAgent",
    "MemoryAgent",
    "SafetyAgent",
    "DigitalDNAAgent",
    "ILFAgent",
    "MutationAgent",
    "AgentProposal",
    "OrganismObserver",
    "PhysiologicalProfile",
    "AdaptiveLevel",
    "AdaptiveLevelRegistry",
    "HarnessUpdate",
    "WeightUpdate",
    "DNAMutationRecord",
    "MutationRegistry",
    "EpigeneticMarker",
    "EpigeneticTag",
    "EpigeneticState",
    "EpigeneticEngine",
    "EvolutionaryMemory",
    "MemoryEntry",
    "ILFRegulator",
    "MutationVerdict",
    "NeurogenesisPipeline",
    "NewModuleSpec",
    "RollbackManager",
    "RollbackPlan",
    "QuantumEvolutionEngine",
    "QuantumOracle",
    "QAOASelector",
    "QuantumKernelClassifier",
]
